"""add user_id to cards

Revision ID: 4ce86b934097
Revises: d6366fd03714
Create Date: 2021-01-21 14:19:06.581365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce86b934097'
down_revision = 'd6366fd03714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'user_id')
    # ### end Alembic commands ###
